### ISSUE TITLE
Sem conteúdo. 

### ISSUE THREAD

**Issue by maojsm** [dotnet/docs.pt-br#102]
Não serve pra nada, são apenas obviedades escritas.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: ecb313b6-34aa-6333-3228-4f66b10ceb3b
* Version Independent ID: f030777f-896e-2e9b-e347-0c600229243a
* Content: [Controles dos Windows Forms usados para listar opções](https://docs.microsoft.com/pt-br/dotnet/framework/winforms/controls/windows-forms-controls-used-to-list-options)
* Content Source: [docs/framework/winforms/controls/windows-forms-controls-used-to-list-options.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/framework/winforms/controls/windows-forms-controls-used-to-list-options.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Olá, @maojsm 
Realmente gostaríamos de receber seu comentário e vamos melhorar sua experiência no docs.microsoft.com. Porém precisamos de mais informações para podermos endereçar seus comentários. Você poderia fornecer informações mais detalhadas e explicar seu comentário?
Atenciosamente,
Equipe Internacional do Microsoft DOCS

**Comment by mairaw** [comment]
Eu diria que a função dessa página é apenas listar os artigos que fazem parte daquela seção.
Acho que seria bom entender o que ele estava procurando. Mas em todo o caso não seria um problema na tradução, mas do conteúdo original.

**Comment by CeciAc** [comment]
Olá, @maojsm 
Obrigado novamente por seu comentário.
Infelizmente, ainda não temos as informações necessárias e não conseguimos processar seu comentário. Estamos fechando este problema do GitHub no momento, mas pedimos que você envie mais comentários no futuro.
Atenciosamente,
Equipe Internacional do Microsoft DOCS
