### ISSUE TITLE
nenhum

### ISSUE THREAD

**Issue by afonsocm** [dotnet/docs.pt-br#106]
Ótimo  documento

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 77d9cc47-5caf-184a-0ad6-cb968850be7a
* Version Independent ID: f058bf17-04e9-9e23-05c7-66c1864445ad
* Content: [Instrução switch do C#](https://docs.microsoft.com/pt-br/dotnet/csharp/language-reference/keywords/switch)
* Content Source: [docs/csharp/language-reference/keywords/switch.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/language-reference/keywords/switch.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Olá, @afonsocm 

Seus comentários são muito bem-vindos. Ficamos felizes em ver que sua experiência com nossa documentação atende às suas expectativas. 

Incentivamos você a fornecer seus comentários valiosos para que possamos continuar melhorando sua experiência.

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
