### ISSUE TITLE
Hello Word

### ISSUE THREAD

**Issue by pablohenriquesc** [dotnet/docs.pt-br#107]
Bom, é a introdução é legal para iniciantes, porem os termos técnicos que dão um dificultada, mas esta bem trabalhado e ajuda na fixação para quem está iniciando agora.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 3d841900-8699-af9b-f879-c5cf9b54f21e
* Version Independent ID: 2d85eae9-01e1-17af-b282-715ec3dc0dcb
* Content: [Tutorial interativo de C# Olá, Mundo – introdução ao C#](https://docs.microsoft.com/pt-br/dotnet/csharp/tutorials/intro-to-csharp/hello-world?tutorial-step=7)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/hello-world.yml](https://github.com/dotnet/docs.pt-br/blob/live-sxs/docs/csharp/tutorials/intro-to-csharp/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @pablohenriquesc 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continually improve your experience.

Kind regards,
Microsoft DOCS International Team

**Comment by pablohenriquesc** [comment]
Prolancer
99freelas
Trampos.co
GetNinjas
Freelance Web designer
Shoe Boxed
Workana
We Do Logos
Meu Redator

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FranciscoOssianFOLN** [comment]
Sim, o mais correto seria uma observação no site afirmando que é desejado um conhecimento de lógica para programação antes (não impedindo o usuário), mas deixa mais claro seus possíveis impedimentos. Até pois aqui é no formato mais para um documentário (mais direto).

**Comment by pablohenriquesc** [comment]
Bom dia, Me desculpe o e-mail foi endereçado incorreto.
________________________________
