### ISSUE TITLE
Article is not translated to portuguese

### ISSUE THREAD

**Issue by lucasnobredev** [dotnet/docs.pt-br#114]
Article is not translated to portuguese. It's all in english.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 49bd5a1a-9074-0d01-f6fc-5647f6c0fb2f
* Version Independent ID: f20891dd-86a4-ec9f-0162-fd87b85612c9
* Content: [Operadores nulos condicionais – referência do C#](https://docs.microsoft.com/pt-br/dotnet/csharp/language-reference/operators/null-conditional-operators)
* Content Source: [docs/csharp/language-reference/operators/null-conditional-operators.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/language-reference/operators/null-conditional-operators.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@lucasnobredev eu estou vendo o conteúdo em português

![image](https://user-images.githubusercontent.com/12971179/53220413-3f901400-3619-11e9-96e2-43196e9a0485.png)

Será que você não está com a opção Ler em inglês selecionada?

**Comment by mairaw** [comment]
One thing I'm not seeing though is the English content when I hover over the Portuguese content. Can you check that @JasonCard?

**Comment by lucasnobredev** [comment]
@mairaw Desculpa! Eu tinha certeza que havia verificado a opção de Ler em inglês. Vou fechar a issue.
