### ISSUE TITLE
Erro ao rodar aplicacao

### ISSUE THREAD

**Issue by rique-scs** [dotnet/docs.pt-br#116]
Estou recebdno o seguinte erro ao tentar rodar a aplicacao na chamada var model = pipeline.Fit(dataView); : 

System.InvalidOperationException: 'Splitter/consolidator worker encountered exception while consuming source data'
InvalidOperationException: Could not parse value &lt;head&gt; in line 9, column Label

Parece ser algo na leitura dos arquivos de teste.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Usar o ML.NET em um cenário de classificação binária de análise de sentimento](https://docs.microsoft.com/pt-br/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by CeciAc** [comment]
Olá, @rique-scs 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
