### ISSUE TITLE
Instalar o .NET Framework 3.5 mesmo tendo versão superior

### ISSUE THREAD

**Issue by gpd38** [dotnet/docs.pt-br#119]
Ao ler sobre este problema, realizei o procedimento descrito acima.
Habilitei o NET Framework 3.5 e o mesmo precisou baixar alguns arquivos. Baixei pelo windows update e infelizmente nenhum dos erros descritos chegou a acontecer. Ocorreu um erro novo "0x80D02002"

Pesquisei este erro e após algumas tentativas de solução meu problema continua... 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Instalar o .NET Framework 3.5 no Windows 10, no Windows 8.1 e no Windows 8](https://docs.microsoft.com/pt-br/dotnet/framework/install/dotnet-35-windows-10#feedback)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by CeciAc** [comment]
Olá, @gpd38 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
