### ISSUE TITLE
Criação de novas documentações

### ISSUE THREAD

**Issue by tbaragao** [dotnet/docs.pt-br#122]
@CeciAc Estava dando uma lida na documentação do SignalR  (AspNet Core) e vi que ainda não existe tradução (atualmente, tudo é traduzido automaticamente). Gostaria de saber qual processo devo seguir para criar os documentos em português e disponibilizá-los aqui?

Já contribui nesse repositório e gostaria de acrescentar e evoluir ainda mais ele. Como estou focado na leitura da documentação do SignalR (AspNet Core) já poderia fazer isso para todo essa documentação.

**Comment by CeciAc** [comment]
Olá, @tbaragao 
 
Agradecemos seus comentários. 
 
Vamos analisar seus comentários e daremos um retorno para você em breve. 
 
Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by CeciAc** [comment]
Hi @tbaragao,

Thank you and we appreciate your contributions.
Unfortunately, we are currently not accepting contributions for content where we are using Machine Translation.
We’re terribly sorry for this inconvenience that you cannot contribute at this time.
We are working on improving our Machine Translation and plan to enable contributions again in the future.

We also understand you would like to have Human Translation for the SignalR documentation in ASP.NET Core. 
We will take this into consideration and look into localizing this documentation in Human Translation in the near future.
We would like to ask for your patience on this matter and let us close this issue for now.

Kind regards,
Microsoft DOCS International Team
Cc @JasonCard @DavidPrio 
#please-translate

**Comment by CeciAc** [comment]
Tradução:

Oi @tbaragao,

Obrigado por suas contribuições.
Infelizmente no momento não estamos aceitando colaboradores para conteúdo onde estamos usando tradução automática.
Sentimos muito pelo inconveniente.
Estamos trabalhando para melhorar nossa tradução automática, e temos planos de habilitar os colaboradores novamente, no futuro.

Também entendemos que você gostaria de ter tradução humana para a documentação do SignalR no ASP.NET Core.
Levaremos isso em consideração e vamos localizar a documentação sobre tradução humana em breve.
Agradecemos a sua paciência. Estamos dando baixa nesse problema, por hora.

Atenciosamente,
Equipe Internacional do Microsoft DOCS
Cc @JasonCard @DavidPrio
