### ISSUE TITLE
Command line execution and compilation

### ISSUE THREAD

**Issue by franklynpc** [dotnet/docs.pt-br#126]
Command line execution and compilation how do I create a compilation in programming

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 22951aaa-bfb8-f6e5-5d08-d9fd758bc689
* Version Independent ID: 214492ea-f78e-e1b2-5767-ec3cf32cc54a
* Content: [Olá, Mundo – seu primeiro programa – Guia de programação em C#](https://docs.microsoft.com/pt-br/dotnet/csharp/programming-guide/inside-a-program/hello-world-your-first-program#feedback)
* Content Source: [docs/csharp/programming-guide/inside-a-program/hello-world-your-first-program.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/programming-guide/inside-a-program/hello-world-your-first-program.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @franklynpc 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
