### ISSUE TITLE
Criptografar e descriptografar um arquivo C#

### ISSUE THREAD

**Issue by brunotonet** [dotnet/docs.pt-br#127]
[Insira comentários aqui]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 2a8e441d-cd59-de15-a814-0d86d4cda052
* Version Independent ID: c94ca6d4-7e93-8aac-93d1-7f249c77d243
* Content: [Passo a passo: criar um aplicativo criptográfico](https://docs.microsoft.com/pt-br/dotnet/standard/security/walkthrough-creating-a-cryptographic-application#feedback)
* Content Source: [docs/standard/security/walkthrough-creating-a-cryptographic-application.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/standard/security/walkthrough-creating-a-cryptographic-application.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by CeciAc** [comment]
Olá, @brunotonet 
Realmente gostaríamos de receber seu comentário e vamos melhorar sua experiência no docs.microsoft.com. Porém precisamos de mais informações para podermos endereçar seus comentários. Você poderia fornecer informações mais detalhadas e explicar seu comentário?
Atenciosamente,
Equipe Internacional do Microsoft DOCS

**Comment by CeciAc** [comment]
Olá, @brunotonet
Obrigado novamente por seu comentário.
Infelizmente, ainda não temos as informações necessárias e não conseguimos processar seu comentário. Estamos fechando este problema do GitHub no momento, mas pedimos que você envie mais comentários no futuro.
Atenciosamente,
Equipe Internacional do Microsoft DOCS

**Comment by brunotonet** [comment]
Desculpe, me passei.
Obrigado pela atenção, pode descartar o meu comentário.


Em sex, 5 de jul de 2019 às 15:18, Cecilia Acevedo <notifications@github.com>
escreveu:
