### ISSUE TITLE
There is another very good library 

### ISSUE THREAD

**Issue by vanderleipires** [dotnet/docs.pt-br#129]
"Enums" by Tyler Brinkley: https://github.com/TylerBrinkley/Enums.NET 
It's worth notice the performance and no need additional classes.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: 4a95bf3d-1028-7c9e-5b7c-0733fc6addaa
* Content: [Usando classes Enumeration em vez de tipos enum](https://docs.microsoft.com/pt-br/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types#feedback)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by srvbpigh** [comment]
Hello, @vanderleipires
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @vanderleipires 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
