### ISSUE TITLE
I'm waiting for private properties declared directly in the constructor

### ISSUE THREAD

**Issue by larini** [dotnet/docs.pt-br#130]
[Insira comentários aqui]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [Novidades no C# 8.0 – Guia do C#](https://docs.microsoft.com/pt-br/dotnet/csharp/whats-new/csharp-8#feedback)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @larini 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by mairaw** [comment]
@larini I suggest you visit https://github.com/dotnet/csharplang to make language suggestions.

**Comment by CeciAc** [comment]
Hello, @larini 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team

**Comment by edwardknak** [comment]
I think him want a constructor like this
public class Class1(private int id, private string description)
{
}
and when the class is instantiated this variables are privates for the class
