### ISSUE TITLE
Excelente documentação! Está me ajudando muito!

### ISSUE THREAD

**Issue by drigovz** [dotnet/docs.pt-br#131]
Me chamo Rodrigo Vaz, trabalho com desenvolvimento web utilizando o .NET Framework e estou aprofundando meus conhecimentos sobre o C# para futuramente entrar de cabeça no .NET Core, estou aprendendo e revendo conceitos de maneira clara e direta na documentação da linguagem, parabéns pela documentação! Está me ajudando muito!

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 14618620-83fc-fd68-93a9-03626c76d680
* Version Independent ID: ea7fbbaf-fd41-75cb-28fb-a2f36c8d3967
* Content: [Um tour pelo C# – Guia do C#](https://docs.microsoft.com/pt-br/dotnet/csharp/tour-of-csharp/#feedback)
* Content Source: [docs/csharp/tour-of-csharp/index.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/tour-of-csharp/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @drigovz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Olá, @drigovz,

Seus comentários são muito bem-vindos. Ficamos felizes em ver que sua experiência com nossa documentação atende às suas expectativas.  

Incentivamos você a fornecer seus comentários valiosos para que possamos continuar melhorando sua experiência. 

Atenciosamente,  

Equipe Internacional do Microsoft DOCS
