### ISSUE TITLE
Erro no tempo verbal

### ISSUE THREAD

**Issue by igorsantosamado** [dotnet/docs.pt-br#134]
Nesse trecho: "... Algumas dessas empresas fazer contribuições significativas para o .NET Core no GitHub e fornecem diretrizes sobre a direção de produto como parte do .NET Foundation Technical Steering Group...."

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 581f6cbb-c666-87ee-ab0c-f131baca403c
* Version Independent ID: 9205f603-e1d4-e0eb-1273-f176fcbf520f
* Content: [Sobre o .NET Core](https://docs.microsoft.com/pt-br/dotnet/core/about#feedback)
* Content Source: [docs/core/about.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/core/about.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by srvbpigh** [comment]
Hello, @igorsantosamado
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @igorsantosamado 

Agradecemos seus comentários. 

Nossa equipe linguística analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir https://docs.microsoft.com/pt-br/dotnet/core/about#feedback 

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
