### ISSUE TITLE
Utilização indevida do verbo ser.

### ISSUE THREAD

**Issue by viniciustavanoferreira** [dotnet/docs.pt-br#136]
No trecho: "(...)Conforme mencionado anteriormente nos princípios de Ignorância de Persistência e Ignorância de Infraestrutura, a camada de infraestrutura não deve **ser** "contaminar" a camada de modelo de domínio.(...)".

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 95f3dcd7-3220-e9cf-3ca6-90b1282410ec
* Version Independent ID: 5a30bea5-326b-ea72-59ae-dfef1e190e4a
* Content: [Projetando um microsserviço orientado a DDD](https://docs.microsoft.com/pt-br/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by srvbpigh** [comment]
Hello, @viniciustavanoferreira
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @viniciustavanoferreira 

Agradecemos seus comentários. 

Nossa equipe linguística analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir https://docs.microsoft.com/pt-br/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
