### ISSUE TITLE
Trocar "Versão prévia" por "preview"

### ISSUE THREAD

**Issue by digocesar** [dotnet/docs.pt-br#141]
Alguns lugares foi traduzido "preview" por "versão prévia". Mas nem todos os lugares dá para traduzir porque "preview" já é um termo entendível para software e alguns lugares se refere à tag "preview", então não deveria ser traduzida.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [Controle de versão da linguagem C# – Guia de C#](https://docs.microsoft.com/pt-br/dotnet/csharp/language-reference/configure-language-version?source=docs)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @digocesar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @<nome do GITHUB do colaborador>,  

Agradecemos seus comentários. 
 
Infelizmente, depois de analisar seus comentários, nossa equipe linguística considerou que não estavam totalmente alinhados com nossos critérios de aceitação, porque [De acordo com o glossário devemos usar "versão prévia" para ficar consistente com os demais produtos] 

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by digocesar** [comment]
Mas então se é para manter a coerência os valores latest e latestMajor na tabela também deveriam ser traduzidos, não?
Inclusive tem partes do texto que está escrito "preview" ao se referir à esta opção de configuração.
