### ISSUE TITLE
Formatação

### ISSUE THREAD

**Issue by marianesfg** [dotnet/docs.pt-br#143]
[Insira comentários aqui]

A formatação da seção "Convertendo um objeto StringBuilder em uma cadeia de caracteres" pode ser melhorada para:

Você deve converter o objeto StringBuilder em um objeto String para transmitir a cadeia de caracteres representada pelo objeto StringBuilder para um método que tem um parâmetro String ou exibi-lo na interface do usuário. Você faz essa conversão chamando o método StringBuilder.ToString. O exemplo a seguir chama vários métodos StringBuilder e chama o método StringBuilder.ToString() para exibir a cadeia de caracteres:
---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a634ac12-e1dc-c668-53fb-88c3514e09a2
* Version Independent ID: 331e6baf-e1b6-c1b9-b65b-f61b0f222c47
* Content: [Uso da classe StringBuilder no .NET](https://docs.microsoft.com/pt-br/dotnet/standard/base-types/stringbuilder#feedback)
* Content Source: [docs/standard/base-types/stringbuilder.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/standard/base-types/stringbuilder.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @marianesfg
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @marianesfg 

Agradecemos seus comentários. 

Nossa equipe linguística analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir https://docs.microsoft.com/pt-br/dotnet/standard/base-types/stringbuilder

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
