### ISSUE TITLE
"Pathologies" to "patologias"

### ISSUE THREAD

**Issue by miohana** [dotnet/docs.pt-br#145]
The sentence "Categorizar pathologies em imagens médicas" needs to be written like this: "Categorizar patologias em imagens médicas".
The right way to say "pathology" in portuguese is "patologia".

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: edace175-268c-7428-dad5-95cd974422c3
* Version Independent ID: 707aed84-b636-088a-bf57-1cc5e4f69631
* Content: [O que é ML.NET e como ele funciona? - ML.NET](https://docs.microsoft.com/pt-br/dotnet/machine-learning/how-does-mldotnet-work#feedback)
* Content Source: [docs/machine-learning/how-does-mldotnet-work.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/machine-learning/how-does-mldotnet-work.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by srvbpigh** [comment]
Hello, @miohana
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @miohana,  

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/pt-br/dotnet/machine-learning/how-does-mldotnet-work#feedback.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team
