### ISSUE TITLE
Ajuste de texto

### ISSUE THREAD

**Issue by guiajava** [dotnet/docs.pt-br#155]
Trocar a tradução "com/Main" por "com /main"

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 336f2435-77ae-0b05-bc63-b8c247cd3ee6
* Version Independent ID: 508d1a8c-a060-a668-8f83-eea7f8bd3b3c
* Content: [Erro do compilador CS0017](https://docs.microsoft.com/pt-br/dotnet/csharp/misc/cs0017#feedback)
* Content Source: [docs/csharp/misc/cs0017.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/misc/cs0017.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @guiajava
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Olá, @guiajava ,  

Agradecemos seus comentários. A página em questão foi traduzida por máquina, o que nem sempre é perfeitamente compreensível. Recentemente adicionamos uma opção "Ler em inglês" à direita, que permite alternar para a versão em inglês sem precisar alterar as configurações de idioma.  

Atenciosamente,  

Equipe Internacional do Microsoft DOCS
