### ISSUE TITLE
Comandos não devem ser traduzidos

### ISSUE THREAD

**Issue by guiajava** [dotnet/docs.pt-br#156]
Na lista de comandos básicos os nomes dos comandos estão traduzidos. Porém a ferramenta não suporta tais traduções. Exemplo: dotnet new e não dotnet novo. Aparentemente a tradução foi automática causando o inconveniente.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: b7e47565-cc59-b1a6-24be-0143c550c0b2
* Version Independent ID: c6859ca6-e2b1-3645-872c-60390ffd429a
* Content: [CLI do .NET Core](https://docs.microsoft.com/pt-br/dotnet/core/tools/)
* Content Source: [docs/core/tools/index.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/core/tools/index.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by srvbpigh** [comment]
Hello, @guiajava
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Olá, @guiajava ,  

Agradecemos seus comentários. A página em questão foi traduzida por máquina, o que nem sempre é perfeitamente compreensível. Recentemente adicionamos uma opção "Ler em inglês" à direita, que permite alternar para a versão em inglês sem precisar alterar as configurações de idioma.  

Atenciosamente,  

Equipe Internacional do Microsoft DOCS

**Comment by tdykstra** [comment]
I will apply code style to the commands so that they won't be translated.  Thanks for pointing this out.
