### ISSUE TITLE
Tradução - linguística

### ISSUE THREAD

**Issue by marianesfg** [dotnet/docs.pt-br#157]
[Insira comentários aqui]

No seguinte parágrafo, há um problema (**destacado em negrito**):

Como desenvolvedores, todos nós temos suposições sobre as interfaces do usuário e dados que são formados pelas nossas culturas. Por exemplo, para um desenvolvedor falante de inglês nos Estados Unidos, a serialização de dados de data e hora como uma cadeia de caracteres no formato MM/dd/yyyy hh:mm:ss parece perfeitamente razoável. No entanto, desserializar essa cadeia de caracteres em um sistema em uma cultura diferente **é** provavelmente lançará uma exceção FormatException ou produzirá dados imprecisos. A globalização nos permite identificar essas suposições específicas de culturas e nos certificarmos de que elas não afetem o design ou código de nosso aplicativo.

Sugiro a correção:

Como desenvolvedores, todos nós temos suposições sobre as interfaces do usuário e dados que são formados pelas nossas culturas. Por exemplo, para um desenvolvedor falante de inglês nos Estados Unidos, a serialização de dados de data e hora como uma cadeia de caracteres no formato MM/dd/yyyy hh:mm:ss parece perfeitamente razoável. No entanto, desserializar essa cadeia de caracteres em um sistema em uma cultura diferente provavelmente lançará uma exceção FormatException ou produzirá dados imprecisos. A globalização nos permite identificar essas suposições específicas de culturas e nos certificarmos de que elas não afetem o design ou código de nosso aplicativo.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 90cff6f0-361c-2963-9f9b-afb4fb0dfb62
* Version Independent ID: 608a6cdc-926c-fd78-79e5-8101cfcd61c5
* Content: [Globalização](https://docs.microsoft.com/pt-br/dotnet/standard/globalization-localization/globalization#feedback)
* Content Source: [docs/standard/globalization-localization/globalization.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/standard/globalization-localization/globalization.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by srvbpigh** [comment]
Hello, @marianesfg
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Olá, @marianesfg,   

Agradecemos seus comentários.  

Nossa equipe linguística analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir https://docs.microsoft.com/pt-br/dotnet/standard/globalization-localization/globalization#feedback.   

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários.  

Atenciosamente,  
Equipe Internacional do Microsoft DOCS
