### ISSUE TITLE
Problemas com a tradução de alguns textos

### ISSUE THREAD

**Issue by caiotava** [dotnet/docs.pt-br#161]
Percebi dois erros na tradução, não sei se é possível efetuar a correção. Vi em outras issues que a tradução é feita automaticamente, mas queria destacar os problemas para uma possível correção no tradutor:

```diff
-Por exemplo, quando dotnet publish my_app.csprojvocê my_app.csproj executa, o argumento indica publish que o projeto será publicado e é passado para o comando.
+Por exemplo, quando você executa dotnet publish my_app.csproj, o argumento my_app.csproj indica o projeto que será publicado e é passado para o comando `publish`.
```

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: b7e47565-cc59-b1a6-24be-0143c550c0b2
* Version Independent ID: c6859ca6-e2b1-3645-872c-60390ffd429a
* Content: [CLI do .NET Core](https://docs.microsoft.com/pt-br/dotnet/core/tools/#feedback)
* Content Source: [docs/core/tools/index.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/core/tools/index.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by srvbpigh** [comment]
Hello, @caiotava
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Olá, @caiotava ,  

Agradecemos seus comentários. A página em questão foi traduzida por máquina, o que nem sempre é perfeitamente compreensível. Recentemente adicionamos uma opção "Ler em inglês" à direita, que permite alternar para a versão em inglês sem precisar alterar as configurações de idioma.  

Atenciosamente,  
Equipe Internacional do Microsoft DOCS
