### ISSUE TITLE
Ajuste de tradução

### ISSUE THREAD

**Issue by digocesar** [dotnet/docs.pt-br#164]
Em &lt;herdar&gt; (https://docs.microsoft.com/pt-br/dotnet/csharp/codedoc#inheritdoc) trocar:
"Você pode &lt;inheritdoc&gt; usar a tag para herdar comentários XML de classes básicas,"
por:
"Você pode usar a tag &lt;inheritdoc&gt; para herdar comentários XML de classes bases,"

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 39152ded-70ce-012d-ffc3-a8b1a78f3308
* Version Independent ID: 809078f6-169a-0ffe-5f33-d5a359aeefc5
* Content: [Documentando seu código com comentários em XML](https://docs.microsoft.com/pt-br/dotnet/csharp/codedoc#inheritdoc)
* Content Source: [docs/csharp/codedoc.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/codedoc.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @digocesar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-radelg** [comment]
Olá, @digocesar :

Agradecemos sua contribuição.

No momento, contribuições sobre problemas de tradução com relação ao conteúdo traduzido automaticamente não estão sendo aceitas.
Valorizamos seus comentários e sugestões sobre o conteúdo produzido por tradução humana, usado para treinar os mecanismos de tradução automática. Assim, com o passar do tempo, suas contribuições vão aprimorar a qualidade das traduções humana e automática.
Os tópicos produzidos por tradução humana podem ser diferenciados dos tópicos traduzidos automaticamente pelo valor de metadados ms.translationtype "HT" (versus "MT" para tradução automática) no cabeçalho de cada arquivo de conteúdo.

Agradecemos seu apoio.

Equipe do DOCS Global Experience da Microsoft

cc @JasonCard
