### ISSUE TITLE
F# escrito como "Fixo #"

### ISSUE THREAD

**Issue by lukelima** [dotnet/docs.pt-br#165]
A linguagem F# foi escrita como "Fixo #" na seção "Próximas etapas" do artigo:
```
Projetos de testes de unidade do .NET Core são compatíveis com:
C#
Fixo #
Visual Basic
```
Será necessário corrigir a palavra.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a64f7e75-fbea-18ba-f290-3e5bb3ab0da7
* Version Independent ID: 24639c20-6c3a-738e-2ff8-9a6ee6f232dc
* Content: [Teste de unidade no .NET Core e no .NET Standard - .NET Core](https://docs.microsoft.com/pt-br/dotnet/core/testing/?pivots=xunit)
* Content Source: [docs/core/testing/index.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/core/testing/index.md)
* Product: **dotnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @lukelima
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @lukelima 

Agradecemos sua contribuição.

No momento, contribuições sobre problemas de tradução com relação ao conteúdo traduzido automaticamente não estão sendo aceitas.

Valorizamos seus comentários e sugestões sobre o conteúdo produzido por tradução humana, usado para treinar os mecanismos de tradução automática. Assim, com o passar do tempo, suas contribuições vão aprimorar a qualidade das traduções humana e automática.

Os tópicos produzidos por tradução humana podem ser diferenciados dos tópicos traduzidos automaticamente pelo valor de metadados ms.translationtype "HT" (versus "MT" para tradução automática) no cabeçalho de cada arquivo de conteúdo.

Agradecemos seu apoio.

Equipe do DOCS Global Experience da Microsoft
