### ISSUE TITLE
Correção de tradução

### ISSUE THREAD

**Issue by mateusbrandao** [dotnet/docs.pt-br#192]
[Insira comentários aqui]
Boa noite!
Na parte de "Linguagem intermediária e execução" existe uma frase que talvez esteja com a tradução incorreta.
O documento em inglês tem a frase "there is even a separate specification **for it** that you can read if you're so inclined" e a tradução para português está "Há até mesmo uma especificação separada **para a ti** que você pode ler se estiver tão inclinada.".

Acho que a melhor tradução ficaria "Há até mesmo uma especificação separada **para isso** que você pode ler se estiver tão inclinada." ou 
"Há até mesmo uma especificação separada **para ele** que você pode ler se estiver tão inclinada.".

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 6c021566-b09c-3a48-f14b-209526a428a1
* Version Independent ID: 0561b29e-2239-43bf-2a18-c5c0a2891fcd
* Content: [O que é código gerenciado?](https://docs.microsoft.com/pt-br/dotnet/standard/managed-code)
* Content Source: [docs/standard/managed-code.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/standard/managed-code.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mairaw Could you describe what should be changed here?

**Comment by mateusbrandao** [comment]
Yes. Instead of using "Há até mesmo uma especificação separada **para a ti** que você pode ler se estiver tão inclinada." you  should use  "Há até mesmo uma especificação separada **para isso** que você pode ler se estiver tão inclinada."

**Comment by mairaw** [comment]
I'd even enhance this further like this:
"Há até mesmo uma especificação separada **para isso** que você pode ler se **você tiver interesse**."

@JasonCard

**Comment by JasonCard** [comment]
@mateusbrandao @mairaw Thank you for your feedback. However, as this is machine translation, we will not be fixing individual machine translation issues unless it's a critical error that's misleading. Thank you for your understanding.
cc @gewarren
