### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by leocamello** [dotnet/docs.pt-br#2]
How can I contribute to this repository?

Can I follow the CONTRIBUTING.md instructions in dotnet/docs?

**Comment by italopessoa** [comment]
Hey @leocamello, did you get any answer?

**Comment by mairaw** [comment]
Yes, the instructions will be similar. The only difference is that if the issue is not a translation issue, it needs to be fixed in the source (dotnet/docs) first. But the vendor team that triages the PRs can let you know if that's the case.

Obrigada pelo interesse em contribuir com a nossa documentação!

**Comment by italopessoa** [comment]
@mairaw, The Portuguese version does not have the changes guide line, I'm willing to do this to make it easier for other contributors learn how to make changes, PRs etc. What o you think?

**Comment by mairaw** [comment]
I think it's a good idea. Let me talk to @Sara-Nicolini to see if the Localization team has any plans regarding this first. I don't want you to spend time on something that won't get approved by them later.

**Comment by italopessoa** [comment]
Hi, @mairaw, sorry if I'm bothering you 😆, but do you have any information so far?

**Comment by mairaw** [comment]
Oi @italopessoa. Sorry, forgot to get back to you. I discussed this with @Sara-Nicolini offline and our team is actually putting a contributor guide and I told her that we should cover the localization scenario too. So, don't think you should be spending your time on that. I can paste the link here once that's published.

**Comment by thiagotacito** [comment]
Hello people!

I am initializing projects in github and contributing to this project translating the documentation into my language will be very good, but I have many questions:

1) What are the steps to set up and contribute to the project? Fork, new branch ...
2) How do I become a contributor?
3) Where will I carry out the commits?

**Comment by nokura** [comment]
Thank you @italopessoa for your input. Will you refer to this section for your contribution?
https://docs.microsoft.com/pt-br/contribute/
