### ISSUE TITLE
Excelente conteúdo, objetivo e esclarecedor

### ISSUE THREAD

**Issue by drigovz** [dotnet/docs.pt-br#56]
Show de bola! Muito bom o conteúdo, trabalho com desenvolvimento web em ASP.NET e só agora me interessei em documentar meu código, e esse artigo me ajudou bastante.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 39152ded-70ce-012d-ffc3-a8b1a78f3308
* Version Independent ID: 809078f6-169a-0ffe-5f33-d5a359aeefc5
* Content: [Documentando seu código com comentários em XML](https://docs.microsoft.com/pt-br/dotnet/csharp/codedoc)
* Content Source: [docs/csharp/codedoc.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/codedoc.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by DavidPrio** [comment]
Olá, @drigovz  

Seus comentários são muito bem-vindos. Ficamos felizes em ver que sua experiência com nossa documentação atende às suas expectativas. 

Incentivamos você a fornecer seus comentários valiosos para que possamos continuar melhorando sua experiência.

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
