### ISSUE TITLE
Data para dados

### ISSUE THREAD

**Issue by alrcastro** [dotnet/docs.pt-br#57]
Só um detalhe que o path no exemplo esta como "Data" e no começo foi pedido para criar uma pasta com o nomes de "Dados"

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Usar o ML.NET para prever tarifas de táxi em Nova York (regressão)](https://docs.microsoft.com/pt-br/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/machine-learning/tutorials/taxi-fare.md)
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by LisandroSu** [comment]
Olá, @alrcastro , 

Agradecemos seus comentários. 

Vamos analisar seus comentários e daremos um retorno para você em breve. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/docs #7035](https://github.com/dotnet/docs/issues/7035) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Olá, @alrcastro  

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 

Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/dotnet/docs/issues/7035 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
