### ISSUE TITLE
Versão posterior da biblioteca libcurl3

### ISSUE THREAD

**Issue by gustavo02itpro** [dotnet/docs.pt-br#59]
Como citado acima, é necessário possuir a biblioteca libcurl3 instalada para utilizar o .NET Core em distribuições ubuntu-based. Entretanto, já possuo uma versão posterior a essa, a libcurl4. Haverá alguma incompatibilidade caso esta última seja utlizada ao invés da primeira?
Grato.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 8cfd5cf0-f28e-be49-227a-c2bbe4e57b8d
* Version Independent ID: 016b2a9c-d1c9-6909-df3e-a49db60b7654
* Content: [Pré-requisitos para o .NET Core no Linux](https://docs.microsoft.com/pt-br/dotnet/core/linux-prerequisites?tabs=netcore2x)
* Content Source: [docs/core/linux-prerequisites.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/core/linux-prerequisites.md)
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by LisandroSu** [comment]
Olá, @gustavo02itpro ,

Sua contribuição é muito   bem-vinda. Nossa equipe só pode responder a comentários relacionados à   documentação.
 
Registre os comentários do seu   produto usando o botão "Enviar Comentários do   Produto" na parte inferior da página de   DOCS.

Se você tiver comentários   relacionados à documentação, fique à vontade para registrá-los por meio deste   canal.
 
Agradecemos sua contribuição   aos nossos artigos.

Atenciosamente,
Equipe Internacional do   Microsoft DOCS
