### ISSUE TITLE
Comando "CreateOrderCommand" não existe no código-fonte linkado

### ISSUE THREAD

**Issue by MarcoNicolodi** [dotnet/docs.pt-br#61]
Na seção "Eliminando a duplicação de eventos de mensagem no nível do EventHandler" há um link para o código fonte, falando sobre o "CreateOrderCommand", que não existe no arquivo. 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 384e5c2c-d3ba-b5ba-260b-65b8e900b78e
* Version Independent ID: a561cbc7-1e00-5732-e298-d9863f85191c
* Content: [Assinando eventos](https://docs.microsoft.com/pt-br/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events)
* Content Source: [docs/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events.md)
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by MarcoNicolodi** [comment]
Provavelmente também a lógica citada no texto foi passada para dentro do handler do mediatr e não está mais no arquivo linkado, mas é preciso olhar com mais atenção. No momento estou no trabalho e não posso me aprofundar.

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/docs #6938](https://github.com/dotnet/docs/issues/6938) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Olá, @MarcoNicolodi ,

Sua contribuição é muito   bem-vinda. Seus comentários são relacionados à documentação original.
 
Portanto, estamos migrando   este problema para o repositório em inglês. Verifique o status do problema   aqui – https://github.com/dotnet/docs/issues/6938.

Agradecemos sua contribuição   aos nossos artigos.

Atenciosamente,
Equipe Internacional do   Microsoft DOCS
