### ISSUE TITLE
Automatic tranlation is so annoing. 

### ISSUE THREAD

**Issue by ederbond** [dotnet/docs.pt-br#63]
I hate when I google for a help and get docs.microsoft.com automatic translated to my language (pt-BR) every time I click on a link on the web.  It would be nice if I can have a global setting for this site where I can opt to always see it in en-US regardless from where do I come from (Brazil, pt-BR or whaterver).

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 45700e86-2a3d-7d33-1f71-65a42352f17e
* Version Independent ID: ab800efe-2f72-7a85-ba5a-90ff3f4233e3
* Content: [Visão geral das propriedades anexadas](https://docs.microsoft.com/pt-br/dotnet/framework/wpf/advanced/attached-properties-overview#feedback)
* Content Source: [docs/framework/wpf/advanced/attached-properties-overview.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/framework/wpf/advanced/attached-properties-overview.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Olá, @ederbond , 

Agradecemos seus comentários. A página em questão foi traduzida por máquina, o que nem sempre é perfeitamente compreensível. Recentemente adicionamos uma opção "Ler em inglês" à direita, que permite alternar para a versão em inglês sem precisar alterar as configurações de idioma. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by LisandroSu** [comment]
Hello, @ederbond , 
 
Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by ederbond** [comment]
I've noticed the "Read in English" button on the top left of the screen. But it would be nice if the option could be saved on the browser (cookie or web storage) so the site could remember my choice on future visits.
