### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by allanRnobre** [dotnet/docs.pt-br#65]
Está com dois retornos!
System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()  =&gt; GetEnumerator();
            {
                return GetEnumerator();
            }

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: eacf9e34-5e7f-37f4-24ad-1dd66fbabb9f
* Version Independent ID: 8ffa29aa-af74-9f39-7e6c-04fd46538177
* Content: [Agrupar resultados por chaves contíguas (LINQ em C#)](https://docs.microsoft.com/pt-br/dotnet/csharp/linq/group-results-by-contiguous-keys)
* Content Source: [docs/csharp/linq/group-results-by-contiguous-keys.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/linq/group-results-by-contiguous-keys.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Obrigada pelo feedback @allanRnobre. Eu criei um Pull request para arrumar o erro:
https://github.com/dotnet/samples/pull/236
