### ISSUE TITLE
Excelente

### ISSUE THREAD

**Issue by cleidsonbsilva** [dotnet/docs.pt-br#68]
Muito prático e simples!

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a379f216-2f6a-a369-6f4d-d655c5c3884d
* Version Independent ID: fdce1eb8-d495-e218-ab65-2e656073b5b3
* Content: [Como usar um menu contextual personalizado com um TextBox](https://docs.microsoft.com/pt-br/dotnet/framework/wpf/controls/how-to-use-a-custom-context-menu-with-a-textbox)
* Content Source: [docs/framework/wpf/controls/how-to-use-a-custom-context-menu-with-a-textbox.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/framework/wpf/controls/how-to-use-a-custom-context-menu-with-a-textbox.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Olá, @cleidsonbsilva, 

Seus comentários são muito bem-vindos. Ficamos felizes em ver que sua experiência com nossa documentação atende às suas expectativas. 

Incentivamos você a fornecer seus comentários valiosos para que possamos continuar melhorando sua experiência.

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
