### ISSUE TITLE
System.Collections.Generic x System.Collections

### ISSUE THREAD

**Issue by maicomoreira** [dotnet/docs.pt-br#80]
Resultado do post o cima não: 
Generic Sort: System.Collections.Generic.List\`1[System.Int32] Time taken: 0.0789ms
Non-Generic Sort: System.Collections.ArrayList Time taken: 2.4324ms
--&gt; NÃO É VERDADE NO ASP NET CORE &lt;-- 
VEJAM:
Generic Sort: System.Collections.Generic.List`1[System.Int32]  
 Time taken: 12.8626ms
Non-Generic Sort: System.Collections.ArrayList  
 Time taken: 2.0332ms

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a25e736b-b6df-d882-5ff1-7d22061ad35b
* Version Independent ID: b5c640cf-8c46-2f44-3196-a504a54a5ded
* Content: [Visão Geral dos Tipos Genéricos (Genéricos)](https://docs.microsoft.com/pt-br/dotnet/standard/generics)
* Content Source: [docs/standard/generics.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/standard/generics.md)
* GitHub Login: @kuhlenh
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #8177](https://github.com/dotnet/docs/issues/8177) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Olá, @maicomoreira,  

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/dotnet/docs/issues/8177. 

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
