### ISSUE TITLE
método OnStart()

### ISSUE THREAD

**Issue by nioshi** [dotnet/docs.pt-br#97]
o método OnStart() sempre fica executando em segundo plano? ou ele apenas é chamado quando o serviço é inicializado?
como eu faria um serviço que sempre ficasse executando? ou teria que usar outro framework?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 75152e30-b486-3ba0-c606-25ada7347b22
* Version Independent ID: e797ddfe-a9d3-93a4-61bd-fd6dc9b8d6b4
* Content: [Criar um aplicativo de serviço Windows no Visual Studio](https://docs.microsoft.com/pt-br/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer)
* Content Source: [docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Olá, @nioshi 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
